### ISSUE TITLE
Trying to create a file via alias on a drive that's not mounted halts Sublime (Windows x32)

### ISSUE THREAD

**Issue by cpkio** [SublimeText/AdvancedNewFile#170]
The title says it all, I think.

I use alias, that binds to drives that arent always mounted. So when alias udx: (sending to U:\Dropbox) is used when new file is created, Sublime halts.

**Comment by FichteFoll** [comment]
I'm afraid that this is the general behavior when trying to access files or drives that aren't accessible. I don't think trying to work around the freeze using an asynchronous thread will help here either, because the behavior will quickly become unexpected and trying to save the file with ST's normal means will very likely cause a freeze anyway.

Closing as wontfix.
